# Generated by Django 3.1.4 on 2021-07-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
