# Generated by Django 3.1.4 on 2021-07-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20210730_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
